### ISSUE TITLE
MLARAM bug raises "ValueError: matrix must be 2-dimensional"

### ISSUE THREAD

**Issue by ghiandonigianmarco** [scikit-multilearn/scikit-multilearn#119]
Hello,

I am trying to use the classifier with a dense matrix (n_samples, n_features) that was converted from a Pandas DataFrame. I tried to use several functions such as "DataFrame.values" and "numpy.matrix(DataFrame)" with no success. The classifier raises the error "ValueError: matrix must be 2-dimensional".

**Comment by niedakh** [comment]
fixed in master
