### ISSUE TITLE
AttributeError: module 'arff' has no attribute 'COO'

### ISSUE THREAD

**Issue by HeartBeautifulSoup** [scikit-multilearn/scikit-multilearn#131]
I used MOA to generate a multi-label data set with errors during the reading process.
`from skmultilearn.dataset import load_from_arff

path_to_arff_file = 'dataset/Drift-RTG8.arff'
label_count = 8
label_location="start"
arff_file_is_sparse = True

x, y, feature_names, label_names = load_from_arff(
    path_to_arff_file,
    label_count=label_count,
    label_location=label_location,
    load_sparse=arff_file_is_sparse,
    return_attribute_definitions=True
)

print(x, y, feature_names[:3], label_names[:3])`

Error message

"E:\Program Files\python\python.exe" "E:\Program Files\pycharm\PyCharm 2017.1.4\helpers\pycharm\_jb_unittest_runner.py" --path "E:/Program Files/multi-Label/test.py"
Testing started at 9:33 ...
Launching unittests with arguments python -m unittest E:/Program Files/multi-Label/test.py in E:\Program Files\multi-Label
Traceback (most recent call last):
  File "E:\Program Files\pycharm\PyCharm 2017.1.4\helpers\pycharm\_jb_unittest_runner.py", line 35, in <module>
    main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING)
  File "E:\Program Files\python\lib\unittest\main.py", line 100, in __init__
    self.parseArgs(argv)
  File "E:\Program Files\python\lib\unittest\main.py", line 147, in parseArgs
    self.createTests()
  File "E:\Program Files\python\lib\unittest\main.py", line 159, in createTests
    self.module)
  File "E:\Program Files\python\lib\unittest\loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "E:\Program Files\python\lib\unittest\loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "E:\Program Files\python\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "E:\Program Files\multi-Label\test.py", line 13, in <module>
    return_attribute_definitions=True
  File "E:\Program Files\python\lib\site-packages\skmultilearn\dataset.py", line 223, in load_from_arff
    open(filename, 'r'), encode_nominal=encode_nominal, return_type=arff.COO
AttributeError: module 'arff' has no attribute 'COO'

Process finished with exit code 1
Empty test suite.

Drift-RTG8.arff file

@relation 'SYN_Z3.0L8X10S1: -C 8'

@attribute class0 {0,1}
@attribute class1 {0,1}
@attribute class2 {0,1}
@attribute class3 {0,1}
@attribute class4 {0,1}
@attribute class5 {0,1}
@attribute class6 {0,1}
@attribute class7 {0,1}
@attribute nominal1 {value1,value2,value3,value4,value5}
@attribute nominal2 {value1,value2,value3,value4,value5}
@attribute nominal3 {value1,value2,value3,value4,value5}
@attribute nominal4 {value1,value2,value3,value4,value5}
@attribute nominal5 {value1,value2,value3,value4,value5}
@attribute nominal6 {value1,value2,value3,value4,value5}
@attribute nominal7 {value1,value2,value3,value4,value5}
@attribute nominal8 {value1,value2,value3,value4,value5}
@attribute nominal9 {value1,value2,value3,value4,value5}
@attribute nominal10 {value1,value2,value3,value4,value5}

@data

{1 1,4 1,7 1,9 value4,10 value3,11 value5,12 value5,13 value5,14 value5,15 value2,16 value4,17 value4}
{5 1,7 1,8 value5,9 value4,10 value3,11 value4,12 value3,13 value5,14 value3,15 value3,16 value2,17 value5}
{2 1,7 1,10 value3,11 value3,12 value3,13 value3,15 value4,17 value3}
{1 1,2 1,4 1,7 1,8 value4,9 value3,10 value2,11 value4,12 value4,13 value2,14 value5,16 value5}

**Comment by niedakh** [comment]
What's your liac-arff version?

**Comment by HeartBeautifulSoup** [comment]
> 你的liac-arff版本是什么？
My LIC-ARFF is
liac-arff in e:\program files\python\lib\site-packages (2.3.1)
I see that there is no import lic-arff in the source code, but the use of arff.

**Comment by niedakh** [comment]
Liac-arff changed the API i 2.3.1, we'll fix this in a couple of days.

You can get it working, by installing the earlier stable version of liac-arf:
```
pip install liac-arff==2.2.1
```

**Comment by HeartBeautifulSoup** [comment]
> Liac-arff changed the API i 2.3.1, we'll fix this in a couple of days.
> 
> You can get it working, by installing the earlier stable version of liac-arf:
> 
> ```
> pip install liac-arff==2.2.1
> ```

 I’m truly grateful for your help.

**Comment by HeartBeautifulSoup** [comment]
> pip install liac-arff==2.2.1
I have changed the version of liac-arff to 2.2.1, but pycharm still prompts me.
"E:\Program Files\python\python.exe" "E:\Program Files\pycharm\PyCharm 2017.1.4\helpers\pycharm\_jb_unittest_runner.py" --path "E:/Program Files/multi-Label/test.py"
Testing started at 10:17 ...
Launching unittests with arguments python -m unittest E:/Program Files/multi-Label/test.py in E:\Program Files\multi-Label
Traceback (most recent call last):
  File "E:\Program Files\pycharm\PyCharm 2017.1.4\helpers\pycharm\_jb_unittest_runner.py", line 35, in <module>
    main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING)
  File "E:\Program Files\python\lib\unittest\main.py", line 100, in __init__
    self.parseArgs(argv)
  File "E:\Program Files\python\lib\unittest\main.py", line 147, in parseArgs
    self.createTests()
  File "E:\Program Files\python\lib\unittest\main.py", line 159, in createTests
    self.module)
  File "E:\Program Files\python\lib\unittest\loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "E:\Program Files\python\lib\unittest\loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "E:\Program Files\python\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "E:\Program Files\multi-Label\test.py", line 13, in <module>
    return_attribute_definitions=True
  File "E:\Program Files\python\lib\site-packages\skmultilearn\dataset.py", line 223, in load_from_arff
    open(filename, 'r'), encode_nominal=encode_nominal, return_type=arff.COO
AttributeError: module 'arff' has no attribute 'COO'

Process finished with exit code 1
Empty test suite.

**Comment by niedakh** [comment]
So did it work in the end? I am reopening the bug so that we can fix the newest version, I'm subscribed to their repo and I saw the changes that break compatibility, I should be able to fix it by the end of the week.

**Comment by HeartBeautifulSoup** [comment]
The problem has been solved, thank you very much.

**Comment by asghar89** [comment]
How to Solve this error: 
AttributeError: module 'arff' has no attribute 'DENSE'
