### ISSUE TITLE
Weka wrapper issue

### ISSUE THREAD

**Issue by FernandoSaez95** [scikit-multilearn/scikit-multilearn#135]
Hello everyone,

I am trying to run the MEKA wrapper in my python code using skmultilearn. I am using the code in the paragraph 4.2 in http://scikit.ml/meka.html step by step. However, I got this error:

  File "C:\Users\ferna\Anaconda3\lib\site-packages\skmultilearn\ext\meka.py", line 374, in _parse_output
    predictions = self.output_.split(predictions_split_head)[1].split(

IndexError: list index out of range

I have tried the code in three different machines and keep staying. you can find it in the figure attached. 

![code](https://user-images.githubusercontent.com/17518039/49342573-6c0d4300-f65d-11e8-8ded-a0332980a72d.PNG)

What is wrong?

**Comment by niedakh** [comment]
Which version are you using?

**Comment by FernandoSaez95** [comment]
Version 0.1.0 of sk multilearn
Version 1.9.2 of Weka

**Comment by FernandoSaez95** [comment]
Hello, any news?

**Comment by niedakh** [comment]
I can't reproduce this, the extact same code works (minus a different data path). But it seems you have some problem with your installation, as self.output has been renamed to self.output_ in scikit-multilearn 0.1.0. Could you retry with a clean installation of scikit-multilearn? Line 374 of ext/meka.py looks like this in 0.1.0:

```python

        predictions = self.output_.split(predictions_split_head)[1].split(
            predictions_split_foot)[0].split('\n')[1:-1]
```

your error shows that you might have an old version (0.0.5) somewhere.

**Comment by FernandoSaez95** [comment]
I tried reinstalling 0.1.0 and even with the new version 0.2.0 and the error is still there.
Maybe is about the java path? What command do you use in terminal to get the path?

**Comment by niedakh** [comment]
Can you report the new error? Is can't be exactly the same given new versions have different code lines.

**Comment by queirozfcom** [comment]
I had this error and in my case it was because I was using a dataset where the labels are the **first columns** rather than the last ones. So I was using the wrong columns for the labels.

**Comment by FernandoSaez95** [comment]
I finally solved it. The proble was that I need to do pip install liac-arff instead of pip install arff. Thank you all

**Comment by nashatjallad** [comment]
exactly, i had the same problem and I do pip install liac-arff instead of pip install arff as FernandoSaez9 said. Now it runs well
thanks for all

**Comment by ChristianSch** [comment]
I suggest you install the dependencies via the requirements files provided. We explicitly state the `liac-arff` dependency. It is indeed something not that obvious if it causes bugs.

https://github.com/scikit-multilearn/scikit-multilearn/blob/f3839bb7625a2cde5313cdab9dbad6a0013552a3/requirements/base.txt#L3
