### ISSUE TITLE
ModuleNotFoundError: No module named 'skmultilearn.model_selection'

### ISSUE THREAD

**Issue by MaartenKool** [scikit-multilearn/scikit-multilearn#142]
At the risk of being told this is a Stackoverflow issue:

Trying to run: iterative_train_test_split example from the http://scikit.ml/stratification.html page. 

Did a pip install:

scikit-multilearn in /anaconda3/lib/python3.6/site-packages (0.0.5)

would this be the wrong version?

**Comment by Jopepato** [comment]
Hi Maarten!
As you said it's for the version. Currently the library is in the 0.2.0 version
Try to do a pip install --upgrade to the package ^^

**Comment by ChristianSch** [comment]
The stratification was introduced in version [v0.1.0](https://github.com/scikit-multilearn/scikit-multilearn/releases/tag/0.1.0). Can you validate that it works after updating the package?

**Comment by MaartenKool** [comment]
Jose, Christian,

Confirming it works fine after running the upgrade, thanks for the quick reply.

BTW a collegue of mine ran the pip install and he also installed the old version; some wrong pointer in a script somewhere?

Merry Christmas!

Maarten

**Comment by ChristianSch** [comment]
Maybe it was already installed. In this case pip doesn't install the already installed package:
```
λ pip install scikit-multilearn
Requirement already satisfied: scikit-multilearn in /opt/miniconda3/lib/python3.7/site-packages (0.1.0)

λ pip install scikit-multilearn --upgrade
Collecting scikit-multilearn
  Downloading https://files.pythonhosted.org/packages/bb/1f/e6ff649c72a1cdf2c7a1d31eb21705110ce1c5d3e7e26b2cc300e1637272/scikit_multilearn-0.2.0-py3-none-any.whl (89kB)
    100% |████████████████████████████████| 92kB 515kB/s 
Installing collected packages: scikit-multilearn
  Found existing installation: scikit-multilearn 0.1.0
    Uninstalling scikit-multilearn-0.1.0:
      Successfully uninstalled scikit-multilearn-0.1.0
Successfully installed scikit-multilearn-0.2.0

```

**Comment by shm007g** [comment]
same issue with last version
`Requirement already up-to-date: scikit-multilearn in /usr/local/lib/python3.7/site-packages (0.2.0)`

**Comment by shm007g** [comment]
ModuleNotFoundError: No module named 'skmultilearn.problem_transformation'

**Comment by Camus12** [comment]
@shm007g  Could you solve the problem?

**Comment by shm007g** [comment]
@Camus12  Solved long time ago. Can’t remember the solution. Seems dependency version problems. You can search and try more.

**Comment by MFaheem407** [comment]
@shm007g can u remember the solution. I am having the same issue. @Camus12 did you find the solution?

**Comment by MFaheem407** [comment]
@shm007g i solved the issue. Everyone, solution is here https://stackoverflow.com/a/70233495/17108206

**Comment by Alay2812USC** [comment]
@MFaheem407 your given solution is not working for me
