### ISSUE TITLE
MEKA error in meka.predict step

### ISSUE THREAD

**Issue by RuudVelo** [scikit-multilearn/scikit-multilearn#155]
First time post on Github. I am trying to use some models with the MEKA wrapper of your wonderfull scikitmultilearn package. However, I cannot get it to work properly. I have also tried to use the simple example code with the scene dataset on your site (http://scikit.ml/meka.html), but same thing. Can someone please help or maybe this is an error?

I have MEKA properly installed and the GUI runs smoothly.

However when using the scene example it always goes wrong on this part: 
`predictions = meka.predict(sX_test)`

It always gives an error saying:   IndexError: list index out of range
Below you see how I made my code using my own example.  

`from skmultilearn.ext import Meka,download_meka
meka_classpath = download_meka()
meka_classpath
`
Output: MEKA 1.9.2 found, not downloading 
'C:\\Users\\rmc_g\\scikit_ml_learn_data\\meka\\meka-release-1.9.2\\lib\\'

`meka = Meka(
    meka_classifier = "meka.classifiers.multilabel.LC",
    weka_classifier = "weka.classifiers.bayes.NaiveBayes",
    meka_classpath = download_meka(),
    java_command = None)
`
Output: MEKA 1.9.2 found, not downloading

I have also tried the path to java in the java_command, but same place it goes wrong (at .predict)

`from scipy import sparse
sX_train=sparse.csr_matrix(X_train)
sy_train=sparse.csr_matrix(y_train)
sX_test=sparse.csr_matrix(X_test)
sy_test=sparse.csr_matrix(y_test)`

`meka.fit(sX_train, sy_train)`

Output: Meka(java_command='C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath\\java.EXE', meka_classifier='meka.classifiers.multilabel.LC',
 meka_classpath='C:\\Users\\rmc_g\\scikit_ml_learn_data\\meka\\meka-release-1.9.2\\lib\\',
 weka_classifier='weka.classifiers.bayes.NaiveBayes')

 
Just to show you information of my sX and sy files:
sX_train is a <579x58 sparse matrix of type '<type 'numpy.float64'>'
with 28934 stored elements in Compressed Sparse Row format>
sy_train is <579x10 sparse matrix of type '<type 'numpy.float64'>'
with 836 stored elements in Compressed Sparse Row format>
sX_test is <589x58 sparse matrix of type '<type 'numpy.float64'>'
with 29539 stored elements in Compressed Sparse Row format>
sy_test is <589x10 sparse matrix of type '<type 'numpy.float64'>'
with 838 stored elements in Compressed Sparse Row format>

NOW HERE IT GOES WRONG:
`predictions=meka.predict(sX_test)`

Output:
---------------------------------------------------------------------------IndexError                                Traceback (most recent call last)<ipython-input-16-101ff16149f3> in <module>()----> 1 predictions=meka.predict(sX_test)

C:\Users\rmc_g\Anaconda2\lib\site-packages\skmultilearn\ext\meka.pyc in predict(self, X)    
312     
313  self._run(train_arff.name + '.arff', test_arff.name + '.arff', args)
--> 314  self._parse_output()    
315     
316         finally:

C:\Users\rmc_g\Anaconda2\lib\site-packages\skmultilearn\ext\meka.pyc in _parse_output(self)   
372 self._instance_count = int(float(filter(lambda x: '==== PREDICTIONS (N=' in x, self.output_.split(    
373 '\n'))[0].split('(')[1].split('=')[1].split(')')[0]))
--> 374 predictions = self.output_.split(predictions_split_head)[1].split(    
375             predictions_split_foot)[0].split('\n')[1:-1]    376
IndexError: list index out of range

**Comment by RuudVelo** [comment]
It has been solved (thanks to my colleague for also looking at it). The problem was the arff package. This had to be de-installed using pip uninstall arff. After that pip install liac-arff was used. This was the bottleneck.

**Comment by mfarfora** [comment]
Stil i have it
