### ISSUE TITLE
Parametarization of Base learner classifiers

### ISSUE THREAD

**Issue by bogatinovskijasmin** [scikit-multilearn/scikit-multilearn#161]
Hello, 

I am using skmultilearn wrapper around MEKA. I have found troubles of using a different parameterization of the Base algorithms. 
A little investigation in the code I come to the solution to swap the line codes 
```
if self.weka_classifier is not None:
     command_args += ['-W', self.weka_classifier]
command_args += args
```
in _run_meka_command method. 
When initializing the Meka classifier use the parameters as part of the argument weka_classifier.
`meka = Meka(
        meka_classifier = 'meka.classifiers.multilabel.LC', 
        weka_classifier = 'weka.classifiers.trees.J48 -- -M 3',
        meka_classpath = meka_classpath,
        java_command = 'C:\Program Files\Java\jdk1.8.0_152\\bin\java' 
)`
Thank you.
Best regards.

**Comment by ChristianSch** [comment]
https://github.com/scikit-multilearn/scikit-multilearn/pull/186/files
