### ISSUE TITLE
Dependency module arff not installed?

### ISSUE THREAD

**Issue by mdtdev** [scikit-multilearn/scikit-multilearn#163]
I recently installed scikit-multilearn and upon running the first line of the [tutorial](http://scikit.ml/tutorial.html), got an error that the **arff** module is missing. The usual:

``` python
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f00c4ea5393b> in <module>
----> 1 from skmultilearn.dataset import load_dataset

/opt/anaconda/lib/python3.6/site-packages/skmultilearn/dataset.py in <module>
----> 1 import arff
      2 import bz2
      3 import pickle
      4 from scipy import sparse
      5 import hashlib

ModuleNotFoundError: No module named 'arff'
```
Installing arff with pip resolves the error: `pip install arff`.

Since I do not know how dependencies are usually handled in in putting packages on pip, I have no clue where in the [dependencies](https://github.com/scikit-multilearn/scikit-multilearn/tree/master/requirements) it should go. So I can't give you a pull to a fix, sorry!

**Comment by ChristianSch** [comment]
I don't know how you installed the dependencies, but it is well documented [here](https://github.com/scikit-multilearn/scikit-multilearn#dependencies). You're using the wrong `arff` by the way, use `liac-arff` to prevent further problems. See the linked documentation.

**Comment by mdtdev** [comment]
Hmmm. Ok. Thanks for the information. You may want to put that on the [project's webpage](http://scikit.ml/) where it just says `pip install scikit-multilearn`. Most pip packages install their own dependencies.

**Comment by mdtdev** [comment]
BTW -- I do see `liac-arff` listed in the [`base.txt`](https://github.com/scikit-multilearn/scikit-multilearn/blob/master/requirements/base.txt) file. Not sure why it was not handled??

Thanks again!

**Comment by jvalverr** [comment]
You also can use: "pip install arff" for collect and install arff databases

**Comment by ChristianSch** [comment]
`pip install liac-arff` is the correct one.
