### ISSUE TITLE
module not found !

### ISSUE THREAD

**Issue by Rami-Majdoub** [scikit-multilearn/scikit-multilearn#166]
from skmultilearn.neurofuzzy import MLARAM
ModuleNotFoundError: No module named 'skmultilearn.neurofuzzy'

![skmultilearn.neurofuzzy](https://user-images.githubusercontent.com/37843591/56203431-81e83700-6045-11e9-8174-23f78acb913f.PNG)

**Comment by ChristianSch** [comment]
If you would've searched the code, you would find that the documentation is merely outdated, and said code moved to the adapt module: from skmultilearn.adapt import MLARAM

**Comment by ChristianSch** [comment]
closed by https://github.com/scikit-multilearn/scikit-multilearn/commit/d8037e00394cf380c3d731331d1182d8817d799a
