### ISSUE TITLE
AttributeError: 'LabelPowerset' object has no attribute '_label_count'

### ISSUE THREAD

**Issue by imaneAll** [scikit-multilearn/scikit-multilearn#172]
hi,
 Someone can help me solve this problem. My code works fine on my machine but i get the following error when I run it in codaLab:

Y_pred.append(clf.predict_proba(X).toarray()[0])
  File "/usr/local/lib/python2.7/dist-packages/skmultilearn/problem_transform/lp.py", line 181, in predict_proba
    (X.shape[0], self._label_count), dtype='float')
AttributeError: 'LabelPowerset' object has no attribute '_label_count'

**Comment by ChristianSch** [comment]
What versions are you using on either system? Can you verify that?

**Comment by imaneAll** [comment]
Thanks a lot, you're right the versions are different.
