### ISSUE TITLE
Some documentation changes

### ISSUE THREAD

**Issue by ljmartin** [scikit-multilearn/scikit-multilearn#174]
Hi,
Thanks so much for this library, it's going to be really useful. 

I've been going through and trying out most of the classifiers and as I go I've picked up a few things in the documentation that are old or incorrect. I made a pull request for one, but I don't really understand how git works so I'll repeat that here. 

On the MLARAM docs, in the example:
http://scikit.ml/api/skmultilearn.adapt.mlaram.html#skmultilearn.adapt.MLARAM
`from skmultilearn.neurofuzzy import MLARAM`
neurofuzzy should be `adapt`

On the rakelD docs example:
http://scikit.ml/api/skmultilearn.ensemble.rakeld.html#skmultilearn.ensemble.RakelD

```
classifier.fit(X_train, y_train)
prediction = classifier.predict(X_train, y_train)
```
predict method should take `X_test`

On the MLTSVM docs:
http://scikit.ml/api/skmultilearn.adapt.mltsvm.html#skmultilearn.adapt.MLTSVM
```
Parameters:

    X (numpy.ndarray or scipy.sparse) – input features, can be a dense or sparse matrix of size (n_samples, n_features)
    y (numpy.ndaarray or scipy.sparse {0,1}) – binary indicator matrix with label assignments.
```
I think these should both be sparse. I had success with `csr_matrix`'s but couldn't get `ndarray`'s to work.

If I did the pull request correctly then I can continue to make PRs for these things.

cheers

**Comment by ChristianSch** [comment]
Thanks for the work!

1. is fixed by d8037e00394cf380c3d731331d1182d8817d799a
2. is fixed by fc2afe887728e9fe53b86d4724b03fc996e21b23
3. is handled by #170 

Imho these points cover this issue, thus closing for the moment.
