### ISSUE TITLE
AttributeError: module 'arff' has no attribute 'DENSE'

### ISSUE THREAD

**Issue by jvalverr** [scikit-multilearn/scikit-multilearn#176]
I have problems when use arff files . I have errors during the reading process.
'from skmultilearn.dataset import load_from_arff'. I have performed tests with Python 3.7.3 (working from command line) and Python 3.6.5 (working from Jupyter notebook). For both enviroments I have installed [base dependences](https://github.com/scikit-multilearn/scikit-multilearn#dependencies). For liac-arff I have installed version 2.2.1 as suggested [here](https://github.com/scikit-multilearn/scikit-multilearn/issues/131#issuecomment-434141880). However errors persist.

***** I have the following dataset:

@relation example
@attribute a1 numeric
@attribute a2 numeric
@attribute a3 numeric
@attribute a4 numeric
@attribute a5 numeric
@attribute c1{0,1}
@attribute c2{0,1}
@data
1,0,0,0,1,1,1
0,0,1,1,1,0,1
0,0,0,1,0,0,1
0,1,1,1,1,1,0
0,0,0,0,1,0,0

***** I have the following source code:
from skmultilearn.dataset import load_from_arff
arff_file  = 'data/test.arff'
label_count = 2 #number of labels
label_location = "end" #labels are at the end of each row
arff_file_is_sparse = False #data is non-sparse
X, y = load_from_arff(arff_file, label_count=label_count, label_location=label_location, load_sparse=arff_file_is_sparse)

***** Error reported from console with Python 3.7.3:

Traceback (most recent call last):
  File "C:\code.py", line 35, in <module>
    X, y = load_from_arff(arff_file, label_count=label_count, label_location=label_location, load_sparse=arff_file_is_sparse)
  File "C:\.....\Python\Python37\site-packages\skmultilearn\dataset.py", line 216, in load_from_arff
    open(filename, 'r'), encode_nominal=encode_nominal, return_type=arff.DENSE
  File "C:\...\Python\Python37\site-packages\arff.py", line 968, in load
    return_type=return_type)
  File "C:\...\Python\Python37\site-packages\arff.py", line 814, in decode
    raise e
  File "C:\....\Python\Python37\site-packages\arff.py", line 810, in decode
    matrix_type=return_type)
  File "C:\...\Python\Python37\site-packages\arff.py", line 750, in _decode
    attr = self._decode_attribute(row)
  File "C:\...\Python\Python37\site-packages\arff.py", line 676, in _decode_attribute
    raise BadAttributeFormat()
arff.BadAttributeFormat: Bad @ATTRIBUTE format, at line 7. 

***** Error reported from Jupyter Notebook with Python 3.6.5:

AttributeError                            Traceback (most recent call last)
<ipython-input-5-8921ae6f3eb9> in <module>()
      5 arff_file_is_sparse = False #data is non-sparse
      6 
----> 7 X, y = load_from_arff(arff_file, label_count=label_count, label_location=label_location, load_sparse=arff_file_is_sparse)

~\Anaconda3\lib\site-packages\skmultilearn\dataset.py in load_from_arff(filename, label_count, label_location, input_feature_type, encode_nominal, load_sparse, return_attribute_definitions)
    214     if not load_sparse:
    215         arff_frame = arff.load(
--> 216             open(filename, 'r'), encode_nominal=encode_nominal, return_type=arff.DENSE
    217         )
    218         matrix = sparse.csr_matrix(

AttributeError: module 'arff' has no attribute 'DENSE'

Please, I need your help to fix it.

**Comment by Jopepato** [comment]
Hi @jvalverr for the Jupiter version, it is using the module 'arff' and not the 'liac-arff' package. You should remove and uninstall the 'arff' package.
And for the other version, I think that the problem is in the data file. As it says reading the attributes. On the lines of the labels there is no space separating the name from the values. I think that this could be the problem, try modifying your dataset to something like this:
**@Attribute** c1 {0,1}
**@Attribute** c2 {0,1}

**Comment by jvalverr** [comment]
Thanks @Jopepato !!! despite the problem persist in my Jypyter notebook using only arff package as recommended, it is working very well for me at Python 3.7 from console.
