### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by BogusLogin** [scikit-multilearn/scikit-multilearn#21]
Hi,
when I clone the repo and run python setup.py install I obtain the following error:
C:\Anaconda\lib\distutils\dist.py:267: UserWarning: Unknown distribution option:
 'include_package_data'
  warnings.warn(msg)
running install
running build
running build_py
error: package directory 'data' does not exist

kind regards

**Comment by niedakh** [comment]
Thank you for the feedback. I'm working on 0.0.2 and I'm in the middle of the clean up at the time. I need to come up with some automated scenario to make sure a release is working and installable. Your points are very valid, I'll add an apidocs notice on maturity of each methods implementation, clean up and fix installation for 0.0.2 and update the roadmap before the release.

**Comment by niedakh** [comment]
Fixed in 0.0.3, thank your for your help!
