### ISSUE TITLE
GaussianNB Specify Priors w/ OneVsRest, BinaryRelevance Etc

### ISSUE THREAD

**Issue by npschweizer** [scikit-multilearn/scikit-multilearn#220]
It would be nice if there were a way to specify priors in multilabel classification problems using GaussianNB() with OneVsRest and the like. As is passing a list of priors to the model as in the link below yields error "ValueErrors: number of priors must match number of classes"

https://stackoverflow.com/questions/50556191/specify-priors-in-multi-label-naive-bayes-in-python-scikit-learn

Thanks

**Comment by ChristianSch** [comment]
duplicate of https://github.com/scikit-multilearn/scikit-multilearn/issues/126
