### ISSUE TITLE
MlKNN:TypeError: __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by Foreverkobe1314** [scikit-multilearn/scikit-multilearn#224]
When mlknn is used, X is passed in_ train，Y_ When running a train, it always reports an error, saying that one more parameter has been passed. You can obviously pass two parameters. I don't know where the error is

**Comment by FayeDong86** [comment]
!pip uninstall scikit-learn -y
!pip install scikit-learn==0.24.1

Use the older version can help

**Comment by nvkulkarni21** [comment]
What is the version for scikit-multilearn package? I still get the same error. Updated scikit-learn==0.24.1 and scikit-multilearn==0.2.0

**Comment by nvkulkarni21** [comment]
Hello, scikit-learn==0.24.1 and scikit-multilearn==0.2.0 worked for me. Probably you need to restart a session, this helped me.

**Comment by Foreverkobe1314** [comment]
Thank you,I get it.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "scikit-multilearn/scikit-multilearn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 晚上8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [scikit-multilearn/scikit-multilearn] MlKNN:TypeError: __init__() takes 1 positional argument but 2 were given (Issue #224)





 
Hello, scikit-learn==0.24.1 and scikit-multilearn==0.2.0 worked for me. Probably you need to restart a session, this helped me.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Alex-Bujorianu** [comment]
Fixed in pull request #229 which I have merged.

**Comment by nina96** [comment]
I was trying to run multilearn in kaggle but i was getting same error. Updating sklearn to older version didn't seem to work for me. Can anyone please tell me what can I do to make it work?

**Comment by Akhil-77** [comment]
This issue is still not fixed it still shows the error
