### ISSUE TITLE
Cannot install whatsoever

### ISSUE THREAD

**Issue by ChristianSch** [scikit-multilearn/scikit-multilearn#23]
Hey there,

Neither `pip install $tarball`, `pip install scikit-multilearn` or running `python setup.py build && python setup.py install` in the cloned repo (with the fix suggested in #21) does the magic. So now I'm moving the `skmultilearn` folder to my project. I'd say there is currently no way to install this project properly. Any suggestions/input?

**Comment by niedakh** [comment]
I've fixed the bug preventing install but I'm still having import problems after pip install worked, I should be able to clean up my local repo into a working release sometime in the next days.

**Comment by niedakh** [comment]
Fixed in 0.0.3, thank your for your help!
