### ISSUE TITLE
random_state not working in IterativeStratification

### ISSUE THREAD

**Issue by tetris69** [scikit-multilearn/scikit-multilearn#234]
Hi,

I need to use the random_state parameter to have reproductible outcome. 

When initializing the `IterativeStratification` class with a random state, it's super class `_BaseKFold` throws an error because `shuffle` is set to `False`. So if it is needed to not shuffle, I suggest not passing the random_state up. If we don't care, well I suggest setting shuffle to True if a seed is provided.

Thank you

![image](https://user-images.githubusercontent.com/11821842/159580879-dc305de5-4cce-4265-b912-4bbbef679906.png)

**Comment by ChristianSch** [comment]
closing as duplicate, see #251
