### ISSUE TITLE
Compatibility with newer scikit-learn versions

### ISSUE THREAD

**Issue by jstet** [scikit-multilearn/scikit-multilearn#308]
Hey everyone, thank you kindly for developing this helpful package. I would like to bring to your attention a compatibility issue occuring when using GridSearchCV with the Binary Relevance and LabelPowerset methods.

It has been described before here: https://github.com/scikit-learn/scikit-learn/issues/28565

Apparently, scikit-multilearn is not fully compatible with the latest few versions of scikit-learn.

**Comment by northern-64bit** [comment]
Thanks for mentioning this @jstet !

I'll try to work on it and fix it. Sadly this repo is unmaintained, so I started a follow up library found here with a few bug fixes and improvements: https://github.com/scikit-multilearn-ng/scikit-multilearn-ng

**Comment by northern-64bit** [comment]
Btw. feel free to open new issues directly in the new repository

**Comment by jstet** [comment]
Thanks :)

**Comment by northern-64bit** [comment]
@jstet it should now be fixed. It also applied for other classifiers as well. I'll release a new version with the fix during the weekend. Until then you can use it from the library source code if you need it sooner :)

Thanks again for raising the issue!

**Comment by jstet** [comment]
Thanks, works perfectly with the ng package!
