### ISSUE TITLE
Python 2 vs Python 3

### ISSUE THREAD

**Issue by queirozfcom** [scikit-multilearn/scikit-multilearn#43]
What are the plans regarding python 2 vs python 3? Stick with python 2 for the time being?

**Comment by niedakh** [comment]
the plan is to release 0.0.2 as soon as possible maybe this weekend, as there's a 1,5 yr gap since last release and then focus on python 3 and adding some classifiers, also setting up a google group for us to communicate

i think 0.0.3 should fully support both python2 and 3.

**Comment by queirozfcom** [comment]
I see @niedakh. Slack and Gitter (maybe also #irc) are very also good for communication. I will close this then.
