### ISSUE TITLE
Cannot import BinaryRelevance

### ISSUE THREAD

**Issue by mdtdev** [scikit-multilearn/scikit-multilearn#54]
The following code, based on [this section](http://scikit.ml/api/classify.html#problem-transformation) of the docs, does not run and the error is not clear (to me!):

```python
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.naive_bayes import GaussianNB
```

This code returns the following `ImportError`:

```
ImportError                               Traceback (most recent call last)
<ipython-input-29-6a0165cb8005> in <module>()
----> 1 from skmultilearn.problem_transform import BinaryRelevance
      2 from sklearn.naive_bayes import GaussianNB

D:\XXX\Anaconda2\lib\site-packages\skmultilearn\problem_transform\__init__.py in <module>()
      9 """
     10 
---> 11 from .br import BinaryRelevance
     12 from .cc import ClassifierChain
     13 from .lp import LabelPowerset

D:\XXX\Anaconda2\lib\site-packages\skmultilearn\problem_transform\br.py in <module>()
----> 1 from builtins import range
      2 from ..base.problem_transformation import ProblemTransformationBase
      3 from scipy.sparse import hstack, coo_matrix
      4 from sklearn.utils import check_array
      5 import copy

ImportError: No module named builtins
```

Any ideas of what the problem is?

**Comment by mdtdev** [comment]
Solved it! Needed to import the module `future` from my command line before running the notebook that uses `scikit-multilearn`.
```bash
pip install future
```
This eliminates the error, but I have not fully tested it yet. Is this `future` package a missing requirement for `scikit-multilearn`?

**Comment by ChristianSch** [comment]
What python version are you using? Are you using the most recent update of scikit-multilearn? What are the steps to reproduce this issue? (You are using it in jupyter, and your solution works under what circumstances exactly?)

**Comment by mdtdev** [comment]
Sorry since I was closing it so quickly I stopped adding information. Latest version of the Python 2.7 variant in pip [scikit_multilearn-0.0.5-py2-none-any](https://pypi.python.org/pypi/scikit-multilearn). In python 2.7.11. Problem replicated both in Jupyter and as a script at the command line.

Solution works under all circumstances on my system (Windows 10 and OSX; both at python 2.7.11 I believe but I cannot see the OSX version now).
