### ISSUE TITLE
Loading Arff Data not working

### ISSUE THREAD

**Issue by ameet-1997** [scikit-multilearn/scikit-multilearn#57]
The first line from the official docs pertaining to loading datasets,
from skmultilearn.dataset import Dataset,
shows the error"  ImportError: cannot import name 'Dataset' "

**Comment by ChristianSch** [comment]
Hey there,
the docs are wrong, you can load arff data sets like this:

```
from skmultilearn.dataset import load_dataset
d = load_dataset('enron', 'undivided')
```

Available data sets can be listed like this:
```
from skmultilearn.dataset import available_data_sets
available_data_sets()
```

For more information please see [here](https://github.com/scikit-multilearn/scikit-multilearn/blob/master/skmultilearn/dataset.py).

**Comment by mattalhonte** [comment]
Not working here either, on Python 3.5 with Anaconda.  First time, it failed with trying to load the Standard Library from future.  Monkeypatched that import out with a comment.

Now I'm getting this:
```from skmultilearn.dataset import available_data_sets```
```available_data_sets()```
```
TypeError                                 Traceback (most recent call last)
<ipython-input-73-c3b496b1614f> in <module>()
      1 from skmultilearn.dataset import available_data_sets
----> 2 available_data_sets()

~/miniconda3/envs/py35/lib/python3.5/site-packages/skmultilearn/dataset.py in available_data_sets()
    106     archives = get_dataset_list()
    107     archives = [x.split(';')[-1].split('.')[0].split('-') for x in archives.split('\n')]
--> 108     variants = set()
    109     for a in archives:
    110         if a[0] not in variants:

TypeError: a bytes-like object is required, not 'str'
```

**Comment by ljvmiranda921** [comment]
I think this is the same bytes/string issue regarding the incompatibility between Python 2 and 3.
To the creators, I'm wondering if you are doing an integration test (like with [travis-ci](https://travis-ci.org/)) to atleast check the compatibility.

**Comment by ChristianSch** [comment]
I can replicate this problem for a clean install of `python 3.6`. I'll look into it.

**Comment by niedakh** [comment]
@ChristianSch thank you for the fix!
