### ISSUE TITLE
Possible Indentation Error in the "fixed.py"

### ISSUE THREAD

**Issue by jpzhangvincent** [scikit-multilearn/scikit-multilearn#59]
It seems I can't load the LabelSpacePartitioningClassifier. And it shows the Indention Error in the  "fixed.py" file.

![image](https://user-images.githubusercontent.com/7220686/26963624-6dfaefb6-4ca2-11e7-8163-c64ea6347f98.png)

**Comment by xuf12** [comment]
Yes it was indeed an indentation error. Submitted a PR [here](https://github.com/scikit-multilearn/scikit-multilearn/pull/63).

**Comment by ChristianSch** [comment]
Closing as this has already been handled here: https://github.com/scikit-multilearn/scikit-multilearn/pull/63#issuecomment-330918906. Thanks so much @xuf12 for your contribution, it is appreciated!
