### ISSUE TITLE
requirements.txt is incomplete, lists standard library packages and is thus subject to typosquatting 

### ISSUE THREAD

**Issue by ChristianSch** [scikit-multilearn/scikit-multilearn#72]
doing a clean install of `scikit-multilearn` with `pip -r requirements.txt` fails [1].
the file lists multiple standard library packages (which are not supposed to be installed and normally not available via PyPI) and is missing most of the dependencies the project requires as of today.

typosquatting is a severe attack surface as due to the workings of `setup.py` arbritary code execution is allowed. PR #71 removes the affected packages.

further links:
* https://github.com/pypa/warehouse/issues/2151
* https://www.pytosquatting.org

these standard library packags are affected:
* `base64`
* `bz2`
* `copy`
* `pickle`
* `pkgutil`
* `random`
* `shlex`
* `shutil`
* `subprocess`
* `sys`
* `tempfile`
* `unittest`

[2] lists all packages with the newest versions when doing a clean install. it is to be noted however, that the newest packages likely break things for users, and the lowest possible version (approx.) should be used.

---

[1]:
```
Failed to build pkgutil
Installing collected packages: liac-arff, pygments, wcwidth, six, prompt-toolkit, simplegeneric, decorator, pickleshare, ptyprocess, pexpect, parso, jedi, ipython-genutils, traitlets, ipython, igraph, numpy, pkgutil, scipy, scikit-learn
 Running setup.py install for pkgutil ... error
   Complete output from command /home/$user/.virtualenvs/skml/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-egoyxfuc/pkgutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gy3yfutj-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/$user/.virtualenvs/skml/include/site/python3.6/pkgutil:
   Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "/tmp/pip-build-egoyxfuc/pkgutil/setup.py", line 27, in <module>
       "This is a bogus package that should not be installed\n\n"
   Exception: This is a bogus package that should not be installed
   
   Please read https://www.pytosquatting.org
```

[2]:
```
decorator==4.1.2
future==0.16.0
igraph==0.1.11
ipython
ipython-genutils
jedi==0.11.0
liac-arff==2.1.0
numpy==1.13.1
parso==0.1.0
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
scikit-learn==0.19.0
scipy==0.19.1
simplegeneric==0.8.1
six==1.11.0
traitlets==4.3.2
wcwidth==0.1.7
```

**Comment by niedakh** [comment]
i've merged in the hotfix

**Comment by niedakh** [comment]
@ChristianSch I want to divide [2] into three requirements files:

- requirements-base with all requirements to run python-code classifiers, are available via pip, are multiplatform and are BSD or compatible licenced
- requirements-gpl with the libraries that taint the licence to GPL if used, like igraph
- requirements-meka with requirements that are needed for meka

Does that make sense?

**Comment by ChristianSch** [comment]
Sounds good to me. How about adding requirements-development if applicable?

**Comment by niedakh** [comment]
Will add, at least pytest and hamcrest should go in there. I'll make a subdirectory "requirements" and place all the req files there, and set the requirements.txt to -r requirements/base.txt for people that just want the default least-invasive variant.

**Comment by niedakh** [comment]
@ChristianSch done, with 2be81c1dd4427b50335ac68ef3981ae2c1f77056, if you need anything to be put in any of the files, just commit it in :)

the division is as follows:
- base: everything that installs easily on all platforms, i.e. pip install will work, and is licence compatible
- meka: stuff needed to have meka wrapper working
- gpl: the gpl stuff tainting the licence
- dev: the dev stuff

closing this, as both of your reports have been fixed
