### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ljvmiranda921** [scikit-multilearn/scikit-multilearn#74]
Personally, even if we have the project website, it would be much better if users will also find a good README.md once they landed in this repository. A good README structure should probably contain:

- Introduction
- Features
- Dependencies
- Installation
- Basic Usage
- Contributing
- Cite

What do you think, @ChristianSch, @niedakh? I can also open up a PR for this if you are interested.

**Comment by ChristianSch** [comment]
Yes, I think especially the contribution part is very important. Having a lot of information in the readme saves clicks and suggests some kind of acitivy here. I always feel empty readme's are mirrors or something dumped into github without getting much care.

**Comment by niedakh** [comment]
merged, thank you!
