### ISSUE TITLE
Cannot import IGraphLabelCooccurenceClusterer because have trouble installing graph-tool in Anaconda 

### ISSUE THREAD

**Issue by moon412** [scikit-multilearn/scikit-multilearn#85]
I couldn't find a way to install graph-tool in Anaconda. So the functions using IGraphLabelCooccurenceClusterer cannot be used in Anaconda environment. I am wondering whether there is a way to work around it.

Thanks!

**Comment by ChristianSch** [comment]
Afaik graph-tool support from our side is broken anyway, but it's in the pipeline.

Please see [here](https://anaconda.org/ostrokach/graph-tool) for how to install `graph-tool`.

**Comment by moon412** [comment]
Hi Christian,

Thanks for the reply. After hours of searching last night, I think I finally installed graph-tool in Anaconda. But when I import graph_tool in the Jupiter console, the following error appeared. 

`import graph_tool.all as gt`
```
ImportError                               Traceback (most recent call last)
<ipython-input-4-86968a62f6b1> in <module>()
----> 1 import graph_tool.all as gt

~/anaconda3/lib/python3.6/site-packages/graph_tool/__init__.py in <module>()
    109 
    110 from .dl_import import *
--> 111 dl_import("from . import libgraph_tool_core as libcore")
    112 __version__ = libcore.mod_info().version
    113 

~/anaconda3/lib/python3.6/site-packages/graph_tool/dl_import.py in dl_import(import_expr)
     59 
     60     try:
---> 61         exec(import_expr, local_dict, global_dict)
     62     finally:
     63         sys.setdlopenflags(orig_dlopen_flags)  # reset it to normal case to

~/anaconda3/lib/python3.6/site-packages/graph_tool/__init__.py in <module>()

ImportError: dlopen(/Users/yuezha01/anaconda3/lib/python3.6/site-packages/graph_tool/libgraph_tool_core.so, 9): Symbol not found: _PyClass_Type
  Referenced from: /usr/local/lib/libboost_python.dylib
  Expected in: flat namespace
 in /usr/local/lib/libboost_python.dylib
```

It may have something to do with linking to libboost_python3.dylib rather than libboost_python.dylib as suggested [here](https://github.com/Homebrew/homebrew-science/pull/2616). I will post here if I find a solution. Thanks!

**Comment by moon412** [comment]
I finally decided to use a docker container as suggest [here](https://git.skewed.de/count0/graph-tool/wikis/installation-instructions#installing-using-docker). It fulfills my demand for analysis.
