### ISSUE TITLE
RakelD(LabelPowerset(base_clf)) or RakelD(base_clf)?

### ISSUE THREAD

**Issue by moon412** [scikit-multilearn/scikit-multilearn#87]
I am wondering whether I should put a LabelPowerset() function to wrap the base classifier. I see both cases [here](https://github.com/scikit-multilearn/scikit-multilearn/blob/master/tests/RAkELdTesting.ipynb) with RakelD and [here](http://scikit.ml/api/classify.html) with LabelSpacePartitioningClassifier. 

As what I found earlier, RakelD, RakelO and  LabelSpacePartitioningClassifier cannot directly work with some classifiers (e.g. GaussianNB, MultinomialNB) [here](https://github.com/scikit-multilearn/scikit-multilearn/issues/82) because these base classifiers only take y with one dimension. LabelPowerset is required. 

However, I found they all directly work with DecisionTree and RandomForest because the fit and predict functions can take y with two dimensions [n_samples, n_outputs]. But I found the results are different depending on whether I put LabelPowerset around the tree classifier.

**Comment by ChristianSch** [comment]
I honestly don't know about `LabelSpacePartitioningClassifier`, but from the doc it reads like it's another approach as just LP with a base classifier, hence the different performance.

As per the [rakel paper](http://ieeexplore.ieee.org/document/5567103/):
> A less common problem transformation method considers each different sub-
set of L as a single label. It so learns one single-label classifier
h:X → P(L), where P(L) is the powerset of L, containing all possible label subsets. We will
refer to this method as **Label Powerset (LP) learning**. LP has the advantage of
taking label correlations into account, but suffers from the large number of label
subsets, the majority of which are associated with very few examples.
**This paper proposes an approach that constructs an ensemble of LP classi-
fiers. Each LP classifier is trained using a different small random subset of the
set of labels.** The proposed approach, dubbed RAKEL (RAndom k-labELsets),
aims at taking into account label correlations and at the same time avoiding
the aforementioned problems of LP. Ensemble combination is accomplished by
thresholding the average zero-one decisions of each model per considered la-
bel. The paper investigates the issue of selecting appropriate parameters (subset
size, number of models, threshold) for RAKEL through an experimental study
on three domains concerning protein, image and document classification. Results
of performance comparison against the BR and LP methods are in favor of the
proposed approach.

A while ago the classifiers that work on label subspaces, such as rakel and others, where changed to a unified approach via ` LabelSpacePartitioningClassifier`, as far as I can see. I don't know about using it directly, but you're using it whilst using rakel-o/rakel-d.
I had a quick glance at the code and it seems the `LabelPowerset`, which ought to be part of rakel, was lost or deliberately cleared to allow more freedom. So from my understanding the rakel classifiers ought to be used with `LabelPowerset(BaseClassifier())`.

**Comment by ChristianSch** [comment]
Closing in favor of #82.
