### ISSUE TITLE
mixed use of tabs and spaces in indentation (on version 0.0.5)

### ISSUE THREAD

**Issue by raphaelcampos** [scikit-multilearn/scikit-multilearn#92]
I fixed mine locally, but it should be fixed in the next release.

the comments use tabs as indentation but the remaining code uses spaces.

```
.env/lib/python3.5/site-packages/skmultilearn/ensemble/fixed.py", line 29
    self.label_count = y.shape[1]
                                ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by PokieOlson** [comment]
If anyone else comes across this issue, the PR that fixes this is https://github.com/scikit-multilearn/scikit-multilearn/pull/65.  To use it, uninstall scikit-multilearn, then install it via: `pip install git+https://github.com/scikit-multilearn/scikit-multilearn.git`
