### ISSUE TITLE
Where can I get the data in the provided codes?

### ISSUE THREAD

**Issue by liuwenwen123** [scikit-multilearn/scikit-multilearn#94]
The data in the codes under the folder of "tests", which like "skmultilearn/data/scene-train.dump.bz2" or "meka/data/scene-train.arff", where can I find them?

**Comment by ChristianSch** [comment]
Have you had a look at the docs? http://scikit.ml/api/loading.html

**Comment by liuwenwen123** [comment]
I have looked that.
X_test, y_test = Dataset.load_arff_to_numpy("path_to_data/dataset-train.dump.bz2",
    labelcount = labelcount,
    endian = "big",
    input_feature_type = feature_type,
    encode_nominal = encode_nominal,
    load_sparse = load_sparse)
I didn't know that the sample data like "path_to_data/dataset-train.dump.bz2" is your own data that we couldn't get or the open data that we can get through the folders of the github or the official site.
I didn't know the format of the input data, though I have looked the documentation because of my poor English. I want to see what the format of input data in the github codes, and follow to make my own input data.

Thanks

**Comment by ChristianSch** [comment]
The part "Getting real-world data sets" lists [this repository](http://mulan.sourceforge.net/datasets-mlc.html) as a way to obtain some data. Or you could use sklearn to do that for you (this is old code of mine, so no guarantee it still works):
```
from sklearn.datasets import fetch_mldata

data = fetch_mldata("yeast")
X = data.data
y = data.target.toarray().astype(np.int).T
```
