### ISSUE TITLE
Meka wrapper on Windows

### ISSUE THREAD

**Issue by ekyy2** [scikit-multilearn/scikit-multilearn#95]
Hi everyone,

I am new to Python and the scikit-multilearn repository so thank you in advance for your patience. I tried executing the following code through the Spyder application on Ananconda:

```
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import hamming_loss
from skmultilearn.ext import Meka

X, y = make_multilabel_classification(sparse = True,
    return_indicator = 'sparse')

X_train, X_test, y_train, y_test = train_test_split(X,
    y,
    test_size=0.33)

meka = Meka(
    meka_classifier = "meka.classifiers.multilabel.LC",
    weka_classifier = "weka.classifiers.bayes.NaiveBayes",
    meka_classpath = "C:/Program Files/meka-release-1.9.2-SNAPSHOT/lib/",
    java_command = "C:/Program Files/Java")

meka.fit(X_train, y_train)
```

and got the following error:

```
> meka.fit(X_train, y_train)
> Traceback (most recent call last):
> 
>   File "<ipython-input-2-f6b53f2230d2>", line 1, in <module>
>     meka.fit(X_train, y_train)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\skmultilearn\ext\meka.py", line 153, in fit
>     self.remove_temporary_files([train_arff, classifier_dump_file])
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\skmultilearn\ext\meka.py", line 80, in remove_temporary_files
>     os.remove(file_name.name)
> 
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\EDWARD~1\\AppData\\Local\\Temp\\tmpruhwexku'
```
Perhaps it is something to do with different file closing mechanisms between Windows and Linux? I tried commenting out the os.remove parts of the code and obtained this subsequent error:
```
> meka.fit(X_train, y_train)
> Traceback (most recent call last):
> 
>   File "<ipython-input-3-f6b53f2230d2>", line 1, in <module>
>     meka.fit(X_train, y_train)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\skmultilearn\ext\meka.py", line 163, in fit
>     self.run_meka_command(input_args)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\skmultilearn\ext\meka.py", line 113, in run_meka_command
>     meka_command), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 210, in __init__
>     super(SubprocessPopen, self).__init__(*args, **kwargs)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\subprocess.py", line 709, in __init__
>     restore_signals, start_new_session)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\subprocess.py", line 997, in _execute_child
>     startupinfo)
> 
> FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Any advice would be much appreciated. Let me know if there is more information that I could provide.

Regards,
Edward

**Comment by niedakh** [comment]
this is a valid report, thank you, I've added it to far future work, i am not sure what's wrong and don't have a testing env for windows at the moment, perhaps some else from the team can try tackling it earlier. if not, i'll sit down on it in the future, but not for the next release.

**Comment by ekyy2** [comment]
Thank you for your reply. Not to worry. There's no hurry because a setup which I find to work for now is installing the Linux Subsystem on Windows 10 and installing Anaconda for Python 2.7 (Python 3.6 throws up errors).

**Comment by bifeng** [comment]
same errors. look forward to it!

**Comment by bifeng** [comment]
Using python 2.7, occurring this error:
![_20180405213239](https://user-images.githubusercontent.com/8215563/38368828-ef7ea6f0-3918-11e8-927c-c8241788c049.jpg)

**Comment by ekyy2** [comment]
Hi bifeng,

I presume that you are testing your code on Windows, if so, I did get the same error as you did. If you were to try installing Linux Subsystem on Windows 10 and subsequently Anaconda, it should work fine. Let me know if you need help with the set up. Also, if you were to clone the latest repository (see command below, which is different from the latest release as it incorporates the recent commits, Python 2.7 or Python 3.6 should work.

`pip install git+https://github.com/scikit-multilearn/scikit-multilearn.git`

**Comment by bifeng** [comment]
Thanks for response. Yes, I am testing on windows, how to set it up? 

Thanks again.

**Comment by ekyy2** [comment]
Welcome. It was sometime ago but these were the two links I followed: (1) https://docs.microsoft.com/en-us/windows/wsl/install-win10 to install the Windows Subsystem for Linux followed by the Linux Distribution of your choice (I chose Ubuntu) and (2) https://www.scivision.co/anaconda-python-with-windows-subsystem-for-linux/ for the Anaconda installation. Hope this helps.

**Comment by bifeng** [comment]
Thanks.

**Comment by bifeng** [comment]
Besides, the documents has some error:
$ git clone https://github.com/scikit-multilearn/scikit-multilearn.git
$ cd scikit-multilearn
$ python setup.py  --> changed to sudo python setup.py install

**Comment by ekyy2** [comment]
Nice catch! As for the PermissionError I am not too sure. Maybe it is because you are not running Ubuntu as administrator and/or installed Anaconda as administrator?

**Comment by bifeng** [comment]
That's my home computer, I am using company's computer to check that.

![0d3c4647-5bd6-449c-8be5-17a7c4e4e336](https://user-images.githubusercontent.com/8215563/38599250-46488cf8-3d92-11e8-8b91-ad669d06f40e.jpg)

**Comment by niedakh** [comment]
I've fixed the errors you've reported. Actually I've encountered all of them and fixed one by one, now the windows machines pass meka unit tests on appveyor - https://ci.appveyor.com/project/niedakh/scikit-multilearn 

@ekyy2 @bifeng I think the meka from master should work fine on windows, please test and tell me if it works for you. Closing for now, if something's broken feel free to repoen.

**Comment by ekyy2** [comment]
Hi @niedakh. Thank you for the extensive set of fixes - it does not look trivial. I don't know whether it is just me, maybe @bifeng can confirm, but running the same sort of settings as in my first message, I get similar errors whether it is in Python 3 or Python 2. As per your advice, I am reopening it for now.

Python 3:
> runfile('C:/Users/Edward Yapp/.spyder-py3/temp.py', wdir='C:/Users/Edward Yapp/.spyder-py3')
> C:/Program Files/Java -cp C:/Program Files/meka-release-1.9.2-SNAPSHOT/lib/* meka.classifiers.multilabel.LC -W weka.classifiers.bayes.NaiveBayes -verbosity 0 -split-percentage 100 -t C:\Users\Edward Yapp\AppData\Local\Temp\tmp2tzt4ksr.arff -d C:\Users\Edward Yapp\AppData\Local\Temp\tmpiyl53ymm
> Traceback (most recent call last):
> 
>   File "<ipython-input-1-d8d1212eaea6>", line 1, in <module>
>     runfile('C:/Users/Edward Yapp/.spyder-py3/temp.py', wdir='C:/Users/Edward Yapp/.spyder-py3')
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/Edward Yapp/.spyder-py3/temp.py", line 26, in <module>
>     meka.fit(X_train, y_train)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\skmultilearn\ext\meka.py", line 182, in fit
>     self.run_meka_command(input_args)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\skmultilearn\ext\meka.py", line 128, in run_meka_command
>     universal_newlines=True)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 210, in __init__
>     super(SubprocessPopen, self).__init__(*args, **kwargs)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\subprocess.py", line 709, in __init__
>     restore_signals, start_new_session)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\subprocess.py", line 997, in _execute_child
>     startupinfo)
> 
> FileNotFoundError: [WinError 2] The system cannot find the file specified

Python 2
> runfile('C:/Users/Edward Yapp/.spyder/temp.py', wdir='C:/Users/Edward Yapp/.spyder')
> C:/Program Files/Java -cp C:/Program Files/meka-release-1.9.2-SNAPSHOT/lib/* meka.classifiers.multilabel.LC -W weka.classifiers.bayes.NaiveBayes -verbosity 0 -split-percentage 100 -t c:\users\edward yapp\appdata\local\temp\tmpqccxl6.arff -d c:\users\edward yapp\appdata\local\temp\tmpdgd0kt
> C:\Users\Edward Yapp\Anaconda3\envs\py27\lib\site-packages\arff.py:488: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
>   if v is None or v == u'' or v != v:
> Traceback (most recent call last):
> 
>   File "<ipython-input-1-41a223076038>", line 1, in <module>
>     runfile('C:/Users/Edward Yapp/.spyder/temp.py', wdir='C:/Users/Edward Yapp/.spyder')
> 
>   File "C:\Users\Edward Yapp\Anaconda3\envs\py27\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\envs\py27\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
>     exec(compile(scripttext, filename, 'exec'), glob, loc)
> 
>   File "C:/Users/Edward Yapp/.spyder/temp.py", line 26, in <module>
>     meka.fit(X_train, y_train)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\envs\py27\lib\site-packages\skmultilearn\ext\meka.py", line 182, in fit
>     self.run_meka_command(input_args)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\envs\py27\lib\site-packages\skmultilearn\ext\meka.py", line 128, in run_meka_command
>     universal_newlines=True)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\envs\py27\lib\site-packages\spyder\utils\site\sitecustomize.py", line 210, in __init__
>     super(SubprocessPopen, self).__init__(*args, **kwargs)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\envs\py27\lib\subprocess.py", line 390, in __init__
>     errread, errwrite)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\envs\py27\lib\subprocess.py", line 640, in _execute_child
>     startupinfo)
> 
> WindowsError: [Error 2] The system cannot find the file specified

**Comment by niedakh** [comment]
@ekyy2 java command needs to be a path to java.exe on windows, and' C:/Program Files/Java' is probably the JAVA_HOME, so the windows subprocess tries to execute the directory and fails. Can you retry with a path to the java.exe?

**Comment by ekyy2** [comment]
This is what I tried when I specified the path to java.exe:
```
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import hamming_loss
from skmultilearn.ext import Meka

X, y = make_multilabel_classification(sparse = True,
    return_indicator = 'sparse')

X_train, X_test, y_train, y_test = train_test_split(X,
    y,
    test_size=0.33)

meka = Meka(
    meka_classifier = "meka.classifiers.multilabel.LC",
    weka_classifier = "weka.classifiers.bayes.NaiveBayes",
    meka_classpath = "C:/Program Files/meka-release-1.9.2-SNAPSHOT/lib/",
    java_command = "C:/Program Files/Java/jdk1.8.0_152/bin/java.exe")

meka.fit(X_train, y_train)
```

I obtained the following  error:
> runfile('C:/Users/Edward Yapp/.spyder-py3/temp.py', wdir='C:/Users/Edward Yapp/.spyder-py3')
> C:/Program Files/Java/jdk1.8.0_152/bin/java.exe -cp C:/Program Files/meka-release-1.9.2-SNAPSHOT/lib/* meka.classifiers.multilabel.LC -W weka.classifiers.bayes.NaiveBayes -verbosity 0 -split-percentage 100 -t C:\Users\Edward Yapp\AppData\Local\Temp\tmp9v6k3knc.arff -d C:\Users\Edward Yapp\AppData\Local\Temp\tmp31e632r8
> Traceback (most recent call last):
> 
>   File "<ipython-input-8-d8d1212eaea6>", line 1, in <module>
>     runfile('C:/Users/Edward Yapp/.spyder-py3/temp.py', wdir='C:/Users/Edward Yapp/.spyder-py3')
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/Edward Yapp/.spyder-py3/temp.py", line 26, in <module>
>     meka.fit(X_train, y_train)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\skmultilearn\ext\meka.py", line 182, in fit
>     self.run_meka_command(input_args)
> 
>   File "C:\Users\Edward Yapp\Anaconda3\lib\site-packages\skmultilearn\ext\meka.py", line 136, in run_meka_command
>     raise Exception(self.output + self.error)
> 
> Exception: Error: Could not find or load main class Files.meka-release-1.9.2-SNAPSHOT.lib.*

I checked that the environmental variable JAVA_HOME is not defined; however, I do have the following under my Path system variable: C:\Program Files (x86)\Common Files\Oracle\Java\javapath

**Comment by niedakh** [comment]
@ekyy2  I see, it seems that the meka class path is not quoted in the command, so it catches ""Files/meka-release-1.9.2-SNAPSHOT/lib/", which is very strange, because the quotations worked in the unit tests, I will test this.

**Comment by niedakh** [comment]
@ekyy2 please test with the current master, i changed the way the path is quoted

**Comment by ekyy2** [comment]
Based on your latest push, the meka class path is now successfully quoted:
> runfile('C:/Users/Edward Yapp/.spyder-py3/temp.py', wdir='C:/Users/Edward Yapp/.spyder-py3')
> C:/Program Files (x86)/Common Files/Oracle/Java/javapath/java.exe -cp "C:/Program Files/meka-release-1.9.2-SNAPSHOT/lib/*" meka.classifiers.multilabel.LC -W weka.classifiers.bayes.NaiveBayes -verbosity 0 -split-percentage 100 -t C:\Users\Edward Yapp\AppData\Local\Temp\tmpstp8nxrb.arff -d C:\Users\Edward Yapp\AppData\Local\Temp\tmpza3rzseh

I think that the -t and -d flag options may also need quoting because of that space in the path. Here is a printout of the meka error and output:
> meka.error
> Out[6]: '\njava.lang.Exception: [Error] File does not exist: C:\\Users\\Edward\n'

> meka.output
> Out[5]: "\n\nEvaluation Options:\n\n-h\n\tOutput help information.\n-t <name of training file>\n\tSets training file.\n-T <name of test file>\n\tSets test file (will be used for making predictions).\n-predictions <name of output file for predictions>\n\tSets the file to store the predictions in (does not work with cross-validation).\n-x <number of folds>\n\tDo cross-validation with this many folds.\n-no-eval\n\tSkips evaluation, e.g., used when test set contains no class labels.\n-R\n\tRandomize the order of instances in the dataset.\n-split-percentage <percentage>\n\tSets the percentage for the train/test set split, e.g., 66.\n-split-number <number>\n\tSets the number of training examples, e.g., 800\n-i\n\tInvert the specified train/test split.\n-s <random number seed>\n\tSets random number seed (use with -R, for different CV or train/test splits).\n-threshold <threshold>\n\tSets the type of thresholding; where\n\t\t'PCut1' automatically calibrates a threshold (the default);\n\t\t'PCutL' automatically calibrates one threshold for each label;\n\t\tany number, e.g. '0.5', specifies that threshold.\n-C <number of labels>\n\tSets the number of target variables (labels) to assume (indexed from the beginning).\n-d <classifier_file>\n\tSpecify a file to dump classifier into.\n-l <classifier_file>\n\tSpecify a file to load classifier from.\n-verbosity <verbosity level>\n\tSpecify more/less evaluation output\n\n\nClassifier Options:\n\n-W\n\tFull name of base classifier.\n\t(default: weka.classifiers.trees.J48)\n-output-debug-info\n\tIf set, classifier is run in debug mode and\n\tmay output additional info to the console\n--do-not-check-capabilities\n\tIf set, classifier capabilities are not checked before classifier is built\n\t(use with caution).\n-num-decimal-places\n\tThe number of decimal places for the output of numbers in the model (default 2).\n-batch-size\n\tThe desired batch size for batch prediction  (default 100).\n-\n\n-K\n\tUse kernel density estimator rather than normal\n\tdistribution for numeric attributes\n-D\n\tUse supervised discretization to process numeric attributes\n\n-O\n\tDisplay model in old format (good when there are many classes)\n\n-output-debug-info\n\tIf set, classifier is run in debug mode and\n\tmay output additional info to the console\n--do-not-check-capabilities\n\tIf set, classifier capabilities are not checked before classifier is built\n\t(use with caution).\n-num-decimal-places\n\tThe number of decimal places for the output of numbers in the model (default 2).\n-batch-size\n\tThe desired batch size for batch prediction  (default 100).\n\n"

**Comment by niedakh** [comment]
@ekyy2 could you test the current master please? I've added quoted file paths.

**Comment by ekyy2** [comment]
Hi! I encounter a similar error. meka's fit calls run_meka_command so I think that quoted file paths are also required for fit. If you could please take another look, that would be great. Thank you.

**Comment by niedakh** [comment]
@ekyy2 quoted the paths in fit too in master, could you check if it helped?

**Comment by ekyy2** [comment]
Fit works fine. But now the classifier_dump_file.name for the -l flag in predict needs quoting as well. Hopefully this is the very last commit required!

**Comment by ekyy2** [comment]
I can confirm that it works! Thank you

**Comment by nadhirahannechi** [comment]
hello everybody please can someone explain the main diference between scikit multi learn , tensor flow and meka  and pytorch
