### ISSUE TITLE
General status of the projects

### ISSUE THREAD

**Issue by adrianog** [scikit-multilearn/scikit-multilearn#97]
Hi

I am planning on exploring usage of this libraries, however I am aware of lack of recent activity.

Is the project still active / is there a roadmap?
Regards

**Comment by niedakh** [comment]
We're working on a new release at the moment, you're welcome to join in
too, there's a slack channel and a group of devs,
https://scikit-ml.slack.com

czw., 22 mar 2018 o 01:40 użytkownik AdrianoG <notifications@github.com>
napisał:
