### ISSUE TITLE
Misunderstanding in the documentation of Developing a label space clusterer

### ISSUE THREAD

**Issue by Jopepato** [scikit-multilearn/scikit-multilearn#98]
Hi all,

I was developing a label space clusterer (balanced k-means) and I was having an error while using it because I was returning a 1D array with the indexes of the labels while the classifier was trying to access as a Matrix.
So, I think this part of the documentation may have an error:

> scikit-multilearn follows scikit-learn’s ClustererMixin interface API for a clustering class. scikit-learn concentrates on single-label classification in which one usually performs clustering of the input space X and not the output class space. In scikit-learn the clusterer class is expected to take X and y and provide a clustering of X as an ndarray of n_samples elements, each element corresponding to the id of the cluster to which the observation is assigned, thus if sample no. 3 is assigned to cluster no. 1: result[3] should be equal to 1.

in http://scikit.ml/api/clusterer.html

For solving my error I looked at the code of IGraphLabelCooccurenceClusterer for seeing what it was returning. So I saw this documentation within its function

        Builds a label coocurence_graph using :func:`LabelCooccurenceClustererBase.generate_coocurence_adjacency_matrix` on `y` and then detects communities using a selected `method`.

        Parameters
        ----------
        X : sparse matrix (n_samples, n_features), feature space, not used in this clusterer
        y : sparse matrix (n_samples, n_labels), label space

        Returns
        -------
        partition: list of lists : list of lists label indexes, each sublist represents labels that are in that community

Returns a list of lists which catched me a bit confused as from my understanding the documentation said to return a 1D-array.

At the end I got it to work but it was a bit confussing at the beginning so maybe a change on that part of the documentation could be useful.
Thank you very much for everything (love your work)

**Comment by niedakh** [comment]
@Jopepato in general please return a list of cluster membership, i.e. a membership vector, I will fix this in the upcoming release

**Comment by niedakh** [comment]
@Jopepato also if you want to work on a balanced k-means clusterer, please join us on the slack and we can discuss how it would be best to fit it in scikit-ml.slack.com

**Comment by Jopepato** [comment]
Sure it would be a pleasure! ^^ @niedakh 
But I think I need an invitation for joining the slack. I implemented my balanced k-means based on this paper: https://pdfs.semanticscholar.org/aa6e/e637e9f86148dadbc849983159ea24d2d204.pdf
